from abc import ABC, abstractmethod
from .record import Record
import white_elephant.state.game as Game

class Action(ABC):
    
    #Method to perform the action given the correct inputs which are the game object, an id value, and any values needed to make the change
    @staticmethod
    @abstractmethod
    def do(game: Game.Game) -> Record:
        pass
    
    #Method to undo the action given the correct inputs whicha are the game object and the ActionRecord generated by the actio9n to be undone 
    @staticmethod
    @abstractmethod
    def undo(game: Game.Game, record: Record) -> int:
        pass