name: Lint and Test

on: 
    push:
    pull_request:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set python version
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        - name: Install python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            if [ -f "requirements.txt" ]; then 
                pip install -r requirements.txt; 
            fi

        - name: Lint with ruff
          uses: chartboost/ruff-action@v1
          with:
            src: "./white_elephant/"

        - name: Static type check with pyright
          uses: jakebailey/pyright-action@v2
          with:
            working-directory: "./white_elephant/" 

        - name: Test with pytest
          run: |
            pytest --collect-only /tests
            